"""
The Marlin agent: a LangGraph ReAct agent over `llm` (see app/llm.py), with
tools for structured facts (SQLite, app/fact_store.py) and semantic recall
(FAISS, app/vector_store.py).

Conversation state (message history) is owned by LangGraph's own
`AsyncSqliteSaver` checkpointer, keyed by `thread_id` — we use the
conversation's id as its thread_id, so switching sessions is just passing a
different id in `config`. This lives in the same SQLite file as
app/fact_store.py's `facts` table, but in LangGraph's own tables.

`build_agent()` must be called once at startup (see app/main.py's lifespan)
so the checkpointer's connection can be opened/closed alongside the app.
"""
from contextlib import AsyncExitStack

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage
from langchain.tools import tool, ToolRuntime
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from langchain.agents import create_agent

from app.config import get_settings
from app.fact_store import get_facts, save_fact
from app.llm import llm
from app.vector_store import index_for_recall, search_memory
from app.prompt import SYSTEM_PROMPT
from app.all_tools import TOOLS


_exit_stack = AsyncExitStack()
agent = None





async def build_agent():
    """Open the SQLite checkpointer and compile the agent. Call once at startup."""
    global agent
    checkpointer = await _exit_stack.enter_async_context(
        AsyncSqliteSaver.from_conn_string(get_settings().sqlite_path)
    )
    agent = create_agent(
        llm,
        tools=TOOLS,
        system_prompt=SYSTEM_PROMPT,
        checkpointer=checkpointer,
    )
    return agent


async def close_agent() -> None:
    await _exit_stack.aclose()


def last_turn_messages(all_messages: list[BaseMessage]) -> list[BaseMessage]:
    """`agent.ainvoke()` returns the *entire* checkpointed thread history, not
    just what this call produced. Walk back from the end to the most recent
    HumanMessage (the one this turn just sent) and return everything after
    it — the AI/tool messages generated by this run."""
    for i in range(len(all_messages) - 1, -1, -1):
        if isinstance(all_messages[i], HumanMessage):
            return all_messages[i + 1 :]
    return all_messages


def extract_run_metadata(new_messages: list[BaseMessage]) -> dict:
    """Summarize one agent run for logging: token usage per LLM call, which
    tools were called with what args, and the model(s) that answered.
    `new_messages` should be just the messages produced by this run, e.g.
    from `last_turn_messages()` on an `ainvoke` result, or every
    AIMessage/ToolMessage chunk collected while streaming."""
    tool_calls: list[dict] = []
    llm_calls: list[dict] = []
    total_tokens = {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0}

    for message in new_messages:
        if not isinstance(message, AIMessage):
            continue
        for call in message.tool_calls or []:
            tool_calls.append({"name": call.get("name"), "args": call.get("args")})

        usage = message.usage_metadata
        response_meta = message.response_metadata or {}
        if usage or response_meta:
            llm_calls.append(
                {
                    "model": response_meta.get("model_name") or response_meta.get("model"),
                    "stop_reason": response_meta.get("stop_reason") or response_meta.get("finish_reason"),
                    "usage": usage,
                }
            )
        if usage:
            for key in total_tokens:
                total_tokens[key] += usage.get(key) or 0

    return {
        "llm_calls": llm_calls,
        "tool_calls": tool_calls,
        "total_tokens": total_tokens,
    }
